-- Inventory module schema for Supabase SQL Editor
-- Run this script as-is in Supabase SQL Editor.

create table if not exists products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null,
  stock integer not null default 0,
  unit_price numeric(12,2) not null default 0,
  supplier_id integer not null default 1,
  supplier_name text
);

create table if not exists suppliers (
  id bigint generated by default as identity primary key,
  name text not null,
  category text,
  email text,
  phone text,
  address text,
  rating text
);

create table if not exists purchase_orders (
  id bigint generated by default as identity primary key,
  supplier_name text not null,
  quantity integer not null,
  unit_price numeric(12,2) not null,
  status text not null,
  order_date date not null default current_date
);

create table if not exists app_users (
  username text primary key,
  password text not null,
  role text not null,
  module_code text not null default 'inventory' check (module_code = 'inventory')
);

create table if not exists app_preferences (
  id integer primary key,
  remember_me boolean not null default false,
  remembered_username text
);
