CREATE table employees (
  id bigint generated by default as identity primary key,
  name text not null,
  position text not null,
  department text not null, 
  salary numeric not null
);

CREATE table if not exists hrm_users (
  user_id bigint generated by default as identity primary key,
  username text unique not null,
  password text not null,
  role text not null default 'staff',
  module_code text not null default 'hrm' check (module_code = 'hrm'),
  created_at timestamp default current_timestamp
);

-- Enable Row Level Security (RLS)
ALTER TABLE employees enable row level security;

-- Allow all operations (for development)
drop policy if exists "Allow all access" on employees;
CREATE policy "Allow all access"
on employees
for all
using (true)
with check (true);